global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - name_of_the_alert_file.yml

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      -localhost:9093

scrape_configs:
  - job_name: 'blackbox'
    metrics_path: /probe
    static_configs:
      - targets:
        - https://azure_deploy_link
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115