global:
  scrape_interval: 15s
  evaluation_interval: 10s

rule_files:
  - alert-rules-blackbox-exporter.yml

scrape_configs:
  - job_name: 'blackbox'
    metrics_path: /probe
    static_configs:
      - targets:
        - https://rom-checker.site
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115